travis:
  secure:
    BINSTAR_TOKEN: o0bywK79JNgyLxtuZfAz/Oj8Wby8nSJrHUKDtWjWLPjjkXm782siosjUadJkfJ/tNyoOTumRrBsIJV2WprB/92w+tZnN0AqRMyv4qdZ+6OeSsYOLJyh030WcgUidzOn/exgryuTyxYA8ELFQJR5g3UPjLhq/4atJHBtv0Jgo7NpcLSl9Xgl/H6nfE+PyJxNomwlevAtjdOJLrYjFS0aMm9XqLRcr0h8qW2eqw+2g59r60E+bEQmthFERx3VWTe94gKXQW2rPGEXp/Sz/3Zosl+brUoMoUmmSSP8IipIn6svkfqNbiv6jrEXBQFmocI8eGjAX0vC9r21x2pQNX4XKt0xB1/q6hAolCbFgTPu+xV8cWKdngpjKGT1BIEe8nGP1bErpU8oLO3BmMHMftEJAu22ZUbgOo8uhprUqZ0Eem7sJaAkyRHZp/PyaV9yWe4BqUU88cmKBmJb3Q77AH8hDEhWiFjdY08B6tr0kje7ddOSxYQ2lBsALhW3N8+22YtSiXDzbFnoLj3K+y7RhxJKgJwWKDN1oPSMoJ5tnMS4glQKNVE5coC1qt7kz/W1EfS5eHC6/l7lbmkep6QQjL0Y+W63+tTj3towEWNtaEJpppgL6+TnSrF50qHvJUVDoIxQSbvkmfXft4gaRlzgguJrpxdPn5Trav7MbYIbOmy9L5og=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
